[GLOBAL]
colors = true
plugins = ["hdrhistogram"]
print_stacktrace = true

[stats]
log = true

[test]
use_coverage = false

[coverage-py]
report = ["xml"]
global_report = true

[pytest]
args = ["-vv", "--no-header"]

[oci]
uid_map = ["0:1001:1", "1:100000:65536"]
gid_map = ["0:998:1", "1:100000:65536"]

[umoci]
log = "debug"
